approvedGitRepositories:
  - "**"

catalog:
  vite: "npm:@voidzero-dev/vite-plus-core@latest"
  vite-plus: latest
  vitest: "npm:@voidzero-dev/vite-plus-test@latest"

compressionLevel: mixed

enableGlobalCache: false

enableScripts: true

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.14.1.cjs
