import { fileURLToPath } from "node:url";
import { configDefaults, defineConfig } from "vite-plus";
import { lint, fmt, mergeLint } from "@saeris/configs";

const root = fileURLToPath(new URL(".", import.meta.url));

export default defineConfig({
  root: "docs",
  run: {
    tasks: {
      build: {
        command: "vp run -r build",
        cache: true
      },
      dev: {
        command:
          "vp run --parallel --filter '@mirrordown/remd-*' --filter '@mirrordown/mdit-*' --filter '@mirrordown/markdown-docs' dev",
        cache: false
      }
    }
  },
  fmt: {
    ...fmt,
    ignorePatterns: [
      "templates/**",
      "tests/**/fixtures/**",
      "tests/**/expected/**",
      "docs/public/**/*.md",
      // CHANGELOGs are generated by bumpy in its own markdown style; don't let
      // oxfmt fight it (asterisk vs underscore emphasis, blank-line placement).
      "**/CHANGELOG.md"
    ]
  },
  lint: mergeLint(lint, {
    ignorePatterns: ["templates/**", "docs/public/**/*.md"],
    options: { typeAware: true, typeCheck: true }
  }),
  test: {
    root,
    include: ["tests/**/*.test.ts"],
    exclude: [...configDefaults.exclude, "docs/**"]
  }
});
