// @ts-expect-error astro:content types are generated by `astro sync`/build, which CI's `vp check` does not run
import { defineCollection } from "astro:content";
import { glob } from "astro/loaders";
import { z } from "zod";

const docs = defineCollection({
  loader: glob({ pattern: "**/*.md", base: "./public" }),
  schema: z.object({
    title: z.string(),
    description: z.string().optional(),
    root: z.boolean().optional()
  })
});

export const collections = { docs };
